source 'https://rubygems.org'
gem 'jekyll'
gem 'colorator'
gem 'rake'
#gem 'git'
gem 'rugged'
gem 'typhoeus'
gem 'mercurial-ruby'
gem 'pandoc-ruby'
gem 'redcarpet'
gem 'nokogiri'
gem 'liquid'#, '~> 2.6.2'
gem 'github-markup'
gem 'awesome_print'
gem 'pygments.rb'
gem 'jekyll-sitemap'
